### ISSUE TITLE
Encountered error, can't continue - System.Exception

### ISSUE THREAD

**Issue by N3L3K** [TitansBane/Elysium-Remastered#16]
Tried to reinstall and relaunch everything but the same issue appears.

Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/NVVnQbyQ#gTI5hl7OUdb0SohLhr-rV-2mCJPin-jojFllMtXc8rg failed validation
   at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 226
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 144
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181

**Comment by N3L3K** [comment]
Only issue on Cathedrale Edition. Other works fine.
Sorry
