### ISSUE TITLE
Core Files missing

### ISSUE THREAD

**Issue by wilecoyote** [TitansBane/Elysium-Remastered#19]
Core Files for Elysium Remastered not available for download at Mega.

```
61,75 - Unable to download Elysium Remastered - Core Files.7z
(MegaDownloader+State|https://mega.nz/file/5ZVxDKaQ#Is83DnNFJtQdi3hih5VQI7hFbxlDxH_YO8h3Sn8amlc)
61,75 - Cannot continue, was unable to download one or more archives
61,75 - File hash check (-42) 6196e3143253eedf6c627b66645f3e40847bbff9815306518b065ad5f058b46f
61,75 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
62,11 - File hash check (-42) 6196e3143253eedf6c627b66645f3e40847bbff9815306518b065ad5f058b46f
```

**Comment by Fencedevin** [comment]
I am getting same error

**Comment by Killbot64** [comment]
Why is this marked as completed? not seeing a solution???
