### ISSUE TITLE
Serenity 3DNPC just won't download

### ISSUE THREAD

**Issue by Hextheosis** [TitansBane/Elysium-Remastered#37]
I've tried every single way of attempting to get this work, from simply restarting PC to launching as admin, turning AV of and even searching manually for the file. Is there anyway to get over this issue? It seems a shame for 2000+ files to be unplayable because 1 file refuses to download. Here's the relevant logs:

380.1 - Downloading Serenity 3DNPC BSA Proper.7z
1366.88 - Error reading https://authored-files.wabbajack.org:443/Serenity%203DNPC%20BSA%20Proper.7z_fdc6bf82-2a9c-4ed1-bd1d-1408cb02ef49/parts/436 retrying [1]
1366.9 - System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 24
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.GetWithCDNRetry(Client client, String url, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 155
1464.72 - Error reading https://authored-files.wabbajack.org:443/Serenity%203DNPC%20BSA%20Proper.7z_fdc6bf82-2a9c-4ed1-bd1d-1408cb02ef49/parts/368 retrying [1]
1464.72 - System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 24
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.GetWithCDNRetry(Client client, String url, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 155
1581.36 - Error reading https://authored-files.wabbajack.org:443/Serenity%203DNPC%20BSA%20Proper.7z_fdc6bf82-2a9c-4ed1-bd1d-1408cb02ef49/parts/288 retrying [1]
1581.36 - System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 24
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.GetWithCDNRetry(Client client, String url, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 155
2026.57 - CDN ERROR
2026.57 - System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.<>c__DisplayClass9_0.<<Download>b__0>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 123
--- End of stack trace from previous location ---
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.<>c__DisplayClass9_0.<<Download>b__0>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 123
2026.57 - Loading for alternative to t9h488AZ0Cw=
2026.57 - No alternative for t9h488AZ0Cw= could be found
2026.57 - Downloading Draw 2-45579-1-6-1638321604.7z
2029.39 - Hashing Remaining Archives
2029.39 - Looking for files to hash
2029.58 - Found 2212 total files, 2117 matching filesize
2046.33 - Unable to download Serenity 3DNPC BSA Proper.7z (WabbajackCDNDownloader+State|https://wabbajack.b-cdn.net/Serenity 3DNPC BSA Proper.7z_fdc6bf82-2a9c-4ed1-bd1d-1408cb02ef49)
2046.33 - Cannot continue, was unable to download one or more archives
2046.33 - File hash check (-42) 3f56e79751e6e79f9f18451e6f2819e0dc0217ebb92d74d04ae19c2beab87bcc
2046.34 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
2046.65 - File hash check (-42) 3f56e79751e6e79f9f18451e6f2819e0dc0217ebb92d74d04ae19c2beab87bcc

**Comment by Hextheosis** [comment]
Additionally in my download folder, I have two files downloaded, both 2.6Gb in size named:

Serenity 3DNPC BSA Proper
Serenity 3DNPC BSA Proper_75cad47bac8e157cb90b2ed750279b9b5ecbe3d847e894f4dcb2ede7f8e7e5b7_

But Wabbajack fails to acknowledge these files and continues to attempt a download

**Comment by Hextheosis** [comment]
Issue fixed by simply ticking "Use network workaround (slow)"
