### ISSUE TITLE
CDN ERROR, The SSL connection could not be established

### ISSUE THREAD

**Issue by mbektic** [TitansBane/Elysium-Remastered#46]
While trying to update from v1.7.1 to v1.8.1.
Wabbajack updated today when i started it.
The log shows CDN ERROR and then the same error repeated.

`10.71 - Starting Download of Elysium/elysium
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.06 - CDN ERROR
38.08 - CDN ERROR
46.75 - System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'DecryptError'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable 1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable 1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable 1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 24
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.GetWithRetry(Client client, String url) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 160
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.<>c__DisplayClass9_0.<<Download>b__0>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 123
--- End of stack trace from previous location ---
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.<>c__DisplayClass9_0.<<Download>b__0>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 123`

**Comment by Rhythm-Galaxy** [comment]
Hi,
I'm running into the same problem, what's the fix for this?
